name: causal
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - jupyter-book
  - matplotlib=3.9
  - numpy=2.1
  - pip
  - pandas=2.2
  - polars=1.17
  - python=3.12
  - scikit-learn=1.5
  - statsmodels=0.14
  - pip:
    - causal-learn==0.1.3.9
    - dowhy==0.12
    - econml==0.15.1
    - graphviz
    
